### ISSUE TITLE
i am trying to fetch after select  pdo and it return Word "Array"

### ISSUE THREAD

**Issue by dido97** [lincanbin/PHP-PDO-MySQL-Class#13]
$stmt = $db->prepare("SELECT * FROM child WHERE first_name=? AND password=?");
$stmt->execute(array($name, $Password));
$rows = $stmt->fetchAll(PDO::FETCH_ASSOC);
print $rows;

**Comment by jpiazzal** [comment]
I'm not sure it's the right place to ask this kind of question, [stackoverflow](https://stackoverflow.com/ ) is a better place ;).

However, your problem is that you're trying to display an array ($rows) with a function that output a string ([print](http://php.net/manual/en/function.print.php)). Use [var_dump()](http://php.net/manual/en/function.var-dump.php) or [print_r()](http://php.net/manual/en/function.print-r.php) instead of print().
